# Main file to run teh DDS-Framwork without downloading any files
"""final_safedecoded_llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_rDUO9vLVXeFkompIOSmAUV5QzY1MXW1
"""

!git clone -b dev https://github.com/IamSmokeY/SafeDecoding.git   # use if you want run without downloading full code
!git clone -b dev https://github.com/IamSmokeY/smooth-llm.git      # use if you want run without downloading full code

from huggingface_hub import login
from google.colab import userdata
login(token = userdata.get("hf_token"))

# Commented out IPython magic to ensure Python compatibility.
 %cd SafeDecoding
!pip install -q -r requirements.txt
 %cd ../smooth-llm

"""# Restart the runtime
## In the runtime dropdown there will be restart runtime. After that run the below cells

"""

!pip install -q -r requirements.txt
%cd ../smooth-llm

!python main.py \
    --results_dir ./results \
    --target_model llama3.1 \
    --attack GCG \
    --attack_logfile data/GCG/llama3.1_behaviors.json \
    --smoothllm_pert_type RandomSwapPerturbation \
    --smoothllm_pert_pct 10 \
    --smoothllm_num_copies 10
